QuilixTestTask/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Qulix.Web.Models;
using Qulix.Data.Repository;
using Qulix.Data.Common;

namespace Qulix.Web.Controllers
{
    public class PersonController : Controller
    {
        private IPersonRepository _personRepository = new PersonRepository();


        public ActionResult PersonList()
        {
            IEnumerable<IPerson> persons = _personRepository.GetAllEnities();
            List<PersonModel> personRowModel = persons.Select(x => new PersonModel(x)).ToList();
            return View(personRowModel);
        }



        // GET: Person/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Person/Create
        [HttpPost]
        public ActionResult Create(PersonModel model)
        {
            try
            {
                _personRepository.Create(model);
                return RedirectToAction("PersonList");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            IPerson person = _personRepository.FindById(id);
            PersonModel model = new PersonModel(person);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(int id, PersonModel model)
        {
            try
            {
                _personRepository.Update(id, model);
                return RedirectToAction("PersonList");
            }
            catch
            {
                return View();
            }
        }

        // GET: Person/Delete/5
        public ActionResult Delete(int id)
        {
            PersonModel model = new PersonModel(_personRepository.FindById(id));
            return View(model);
        }

        // POST: Person/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection model)
        {
            try
            {
                _personRepository.DeleteById(id);
                return RedirectToAction("PersonList");
            }
            catch
            {
                return View();
            }
        }
    }
}

QuilixTestTask/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Qulix.Web.Models;
using Qulix.Data.Repository;
using Qulix.Data.Common;

namespace Qulix.Web.Controllers
{
    public class TaskController : Controller
    {
        private ITaskRepository _taskRepository = new TaskRepository();
        private IPersonRepository _personRepository = new PersonRepository();
        //GET: /Task/TaskList
        public ActionResult TaskList()
        {
            ICollection<ITask> tasks = _taskRepository.GetAllEnities();
            TaskListModel taskListModel = new TaskListModel(tasks);
            taskListModel.PersonCount = _personRepository.Count();
            return View(taskListModel);
        }


        // GET: Task/Create
        public ActionResult Create()
        {
            TaskCreateEditModel model = new TaskCreateEditModel();
            return View(model);
        }

        // POST: Task/Create
        [HttpPost]
        public ActionResult Create(TaskCreateEditModel model)
        {
            try
            {
                _taskRepository.Create(model);
                return RedirectToAction("TaskList");
            }
            catch
            {
                return View();
            }
        }

        // GET: Task/Edit/5
        public ActionResult Edit(int id)
        {
            ITask task = _taskRepository.FindById(id);
            TaskCreateEditModel model = new TaskCreateEditModel(task);
            return View(model);
        }

        // POST: Task/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, TaskCreateEditModel model)
        {
            try
            {
                _taskRepository.Update(id, model);
                return RedirectToAction("TaskList");
            }
            catch
            {
                return View();
            }
        }

        // GET: Task/Delete/5
        public ActionResult Delete(int id)
        {
            TaskModel model = new TaskModel(_taskRepository.FindById(id));
            return View(model);
        }

        // POST: Task/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, TaskModel model)
        {
            try
            {
                _taskRepository.DeleteById(id);
                return RedirectToAction("TaskList");
            }
            catch
            {
                return View();
            }
        }
    }
}

QuilixTestTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Qulix Trial</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Qulix Trial", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Persons", "PersonList", "Person")</li>
                    <li>@Html.ActionLink("Tasks", "TaskList", "Task")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>